### ISSUE TITLE
I have 2k resolution monitor and dashbord is not fulscreen i believe it is maybe 1080p can you fix that?

### ISSUE THREAD

**Issue by GIORGIPUNK123** [Exodia-OS/exodia-home-ISO#10]

**Comment by mmsaeed509** [comment]
yeah, the dashboard has been rendered in 1080p <br/> you have to do it yourself

**Comment by GIORGIPUNK123** [comment]
its a bit laggy so i even think to remove hotkey for opening it since its useless

**Comment by mmsaeed509** [comment]
- edit `~/.config/sxhkd/sxhkdrc` 
- Remove these three lines 
  - ![Screenshot_2023-05-01-02-45-04_3840x1080](https://user-images.githubusercontent.com/62524855/235447422-69208e18-81ba-4170-b438-d8a2152d983b.png)
- uninstall dashboard `remove exodia-eww`
