### ISSUE TITLE
Issue update

### ISSUE THREAD

**Issue by likanux** [Exodia-OS/exodia-home-ISO#12]
I'm sorry if I'm wrong I'm new on Linux 
I installed exodia home it worked perfectly at first but when I wanted to update the os I had to accept a lot of corrupt keys and this each time. I click a lot on the keys o and enter.
I couldn't install thunderbird and even a tar.bz2.
I wanted to send you this issue I had to change my os yours seem really good in the future but for now I will keep using just arch.
I wish you good luck and thank you to let us try this os

**Comment by likanux** [comment]
But if you have a solution to avoid all this issues I'll be very excited to use your operating system

**Comment by mmsaeed509** [comment]
here is the [solution](https://exodia-os.github.io/exodia-website/quickstart/post-install)
