### ISSUE TITLE
Booting from USB with UEFI Black screen

### ISSUE THREAD

**Issue by nebfx** [Exodia-OS/exodia-home-ISO#14]
Booting from USB with UEFI not working on Lenovo M720q... presents a black screen

**Comment by mmsaeed509** [comment]
try burn with [balena Etcher](https://etcher.balena.io/)

**Comment by nebfx** [comment]
I did it worked but my mouse doesn't work properly it needs like 3 clicks and i cant close windows… it cant save settings for my extended screens please assist thanks 

Sent from Yahoo Mail for iPhone


On Sunday, July 9, 2023, 1:04 AM, Mahmoud Mohammed ***@***.***> wrote:




try burn with balena Etcher
