### ISSUE TITLE
On checking status of pulseaudio there is something missing

### ISSUE THREAD

**Issue by ghost** [Exodia-OS/exodia-home-ISO#15]
systemctl --user status pulseaudio
● pulseaudio.service - Sound Service
     Loaded: loaded (/usr/lib/systemd/user/pulseaudio.service; disabled; preset: enabled)
     Active: active (running) since Sat 2023-06-10 09:59:35 IST; 11s ago
TriggeredBy: ● pulseaudio.socket
   Main PID: 1094 (pulseaudio)
      Tasks: 8 (limit: 11732)
     Memory: 23.6M
        CPU: 198ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/pulseaudio.service
             ├─1094 /usr/bin/pulseaudio --daemonize=no --log-target=journal
             └─1176 /usr/lib/pulse/gsettings-helper

Jun 10 09:59:34 SystemHacked systemd[643]: Starting Sound Service...
Jun 10 09:59:35 SystemHacked pulseaudio[1094]: stat('/etc/pulse/default.pa.d'): No such file or directory
Jun 10 09:59:35 SystemHacked systemd[643]: Started Sound Service.
Jun 10 09:59:35 SystemHacked pulseaudio[1094]: Could not find org.bluez.BatteryProviderManager1.RegisterBatteryProvider(), is bluetoothd started with experim>

**Comment by amateur-hacker** [comment]
please tell me how to fix it
