### ISSUE TITLE
Don't mounting ssd by UEFI

### ISSUE THREAD

**Issue by clinkuser** [Exodia-OS/exodia-home-ISO#16]
At loading Home Edition with UEFI, system can't mount NTFS ssd. While i use command "mount /dev/sda" it can't be found in /etc/fstab.
I don't know, how to fix it. Please, help!

Since I don't know English very well, I ask you not to find fault with the spelling and grammatical errors (written through a translator)

**Comment by clinkuser** [comment]
Now i try to install Wireless Edition.

**Comment by clinkuser** [comment]
> At loading Home Edition with UEFI, system can't mount NTFS ssd.

USB been formated in NTFS, maybe important

**Comment by clinkuser** [comment]
![IMG_20230623_120723_183](https://github.com/Exodia-OS/exodia-home-ISO/assets/111626295/ebeb9858-8e7e-4d28-a66f-d75f442cbefc)
This is an error while loading Wireless Edition, similar while loading Home Edition

**Comment by clinkuser** [comment]
Huawei Matebook d15

**Comment by mmsaeed509** [comment]
burn the ISO with [**`balena Etcher`**](https://etcher.balena.io/)
