### ISSUE TITLE
i am unable to change my settings like cursor etc and i dont have any apply settings option

### ISSUE THREAD

**Issue by ThinkyMiner** [Exodia-OS/exodia-home-ISO#20]

**Comment by mmsaeed509** [comment]
- edit `~/.config/bspwm/exodia.conf`
- and change these values as you need
- restart `bspwm`  <kbd>ctrl + shift + r</kbd>

![Screenshot_2023-09-23-18-57-56_1920](https://github.com/Exodia-OS/exodia-home-ISO/assets/62524855/6b72e0db-4793-4336-83c6-543e0bd02bcb)

___

or you can change for a specific theme (e.g. VALORANT)

- edit `~/.config/bspwm/themes/VALORANT/theme.conf`
- and change these values as you need
- and select form theme menu <kbd> ctrl + alt + t </kbd> 

![Screenshot_2023-09-23-19-07-38_1920](https://github.com/Exodia-OS/exodia-home-ISO/assets/62524855/babca1c2-468d-481a-8018-15ae620d83e3)
