### ISSUE TITLE
Exodia stuck at booting [ Exodia home ]

### ISSUE THREAD

**Issue by AdribMahmud101** [Exodia-OS/exodia-home-ISO#21]
It got stuck on the splash screen loading . How to fix this ?[
![Uploading 20231219_090621.jpg…]()
](url)

**Comment by mmsaeed509** [comment]
if you boot from a live USB It takes some time to load the kernel, which may take from 1:10 mins

but after installing the system, it will open so faster

**Comment by AdribMahmud101** [comment]
> if you boot from a live USB It takes some time to load the kernel, which may take from 1:10 mins
> 
> but after installing the system, it will open so faster

It was a problem with glibc, system could not found it. I reinstalled it, it's okay now but it's a matter of concern that it takes a lot of time to boot while installing. I hope it will be fixed soon In Sha Allah.
