### ISSUE TITLE
Failed to apply fractional scailing using .xresources

### ISSUE THREAD

**Issue by prateekshukla128** [Exodia-OS/exodia-home-ISO#22]
hello and love from India

i am using exodia os in my laptop which requires 150% scailing 
usually to change scailing in bspwm i put this in my xresources file
Xft.dpi: 150
XTerm.font: 10x20
*termFont: 10x20
Gtk.fontsize: 12
Gtk.scale_factor: 1.5

but this is not working in exodia os (i guess because it have 4 xresources files)

please help

**Comment by mmsaeed509** [comment]
I didn't understand you, but `Xresources` files are located at `~/.Xresources.d/`
if you want to change font, size, etc... 
edit `~/.config/gtk-3.0/settings.ini`

**Comment by prateekshukla128** [comment]
I am using a laptop so i need to apply system wide fractional scailing to 1.5
i do it generally by changing .Xresources file as it does the job 
my question was that which file i have to change in ~/.Xresources.d/ to change my dpi font size and gtk apps scailing

**Comment by prateekgreaat** [comment]
i solved it i just had to edit the xsettingsd file and it made the necessary changes
