### ISSUE TITLE
Is secure boot supported 

### ISSUE THREAD

**Issue by v1ctorio** [Exodia-OS/exodia-home-ISO#23]
I don't really know if you need like some authority cert for supporting secure boot or something 

Do the os rn support secure boot? 

If not, do you plan on doing it?

**Comment by awfixer** [comment]
if Grub does Exodia does

**Comment by mmsaeed509** [comment]
no, secure boot is not supported by Exodia OS

**Comment by mbrehmer-cintact** [comment]
> no, secure boot is not supported by Exodia OS

Why not? Every other distro I have been working with could boot with Secure Boot. So why Exodia does not?
