### ISSUE TITLE
after updating using yay - Cava

### ISSUE THREAD

**Issue by CtorW** [Exodia-OS/exodia-home-ISO#27]
![image](https://github.com/Exodia-OS/exodia-home-ISO/assets/129820204/eb44cf0a-248e-43a2-b173-7d824ab62491)

**Comment by CtorW** [comment]
info : this is a fresh install and i do the "sudo pacman-key --populate" and i update the packages using "yay" after the update i rebooted my system and i get this error in cava

**Comment by mmsaeed509** [comment]
downgrade `iniparser` to `4.2.1`

```bash
sudo downgrade iniparser
```
![Screenshot_2024-05-24-14-34-35_1920](https://github.com/Exodia-OS/exodia-home-ISO/assets/62524855/e0863641-534d-4069-940e-fbf691461905)



then restart `polybar`

```bash
bspbar
```
