### ISSUE TITLE
Screen rotation 

### ISSUE THREAD

**Issue by paulemacedo** [Exodia-OS/exodia-home-ISO#29]
Screen configuration doesn't work at bspwm

![20241104_214743.jpg](https://github.com/user-attachments/assets/16cd3382-22e9-4bc7-9d67-d68415107465)

**Comment by mmsaeed509** [comment]
you can use `arandr` to configure your monitors 
reed [setup custom monitors config](https://exodia-os.github.io/wiki/blog/5-monitors) From Exodia wiki
