### ISSUE TITLE
definition of disaster 

### ISSUE THREAD

**Issue by rzgarespo** [Exodia-OS/exodia-home-ISO#31]
I wish I could erase the day I tested this so-called distro from my memory.
![56799eac64cf8a9ce3b0718bbed38525](https://github.com/user-attachments/assets/f2a6a534-2f60-4bb9-8f41-799f074f01a2)

**Comment by MukundTapaniya** [comment]
Is this distro working well now or not!?

I mean will I be able to use it in my personal computer!?
