### ISSUE TITLE
pgp keyring

### ISSUE THREAD

**Issue by k1lgor** [Exodia-OS/exodia-home-ISO#4]
Hi guys, 
first of all I like very much what have you done, I am big Arch fan. I would be happy to be able to contribute.
Second of all when started initial update, an error occured: _error: package-name: signature from "packager" is unknown trust_ and have to init, verify and refresh the pgp keys.

**Comment by mmsaeed509** [comment]
```bash
sudo pacman-key --populate
```

recommended reading [wiki](https://exodia-os.github.io/exodia-website/quickstart/post-install)

**Comment by mmsaeed509** [comment]
join us in [discord](https://discord.gg/wPDyfR5AV9)
