### ISSUE TITLE
Can't get rid of welcome window

### ISSUE THREAD

**Issue by davidandrewthompson** [Exodia-OS/exodia-home-ISO#6]
Really interested in trying out this distro, but I can't seem to get rid of the welcome window. I've right-clicked and selected "Quit" from the menu. That dismissed the pages in the window, but the blank window remain. I tried Shift-super-q. It works on other windows but not the welcome.

I went into the terminal and ps -ax. Then I tried closing random processes, but nothing seemed to work.

Am I missing something?

**Comment by mmsaeed509** [comment]
to close a window use <kbd>mod + shift + c</kbd>
or force close with `xkill` use <kbd>Ctrl +Alt + Esc</kbd>

and here's the [**`Keybinding`**](https://exodia-os.github.io/exodia-website/Keybinding)


also, if you want to disable auto open `Exodia Help` app

edit `~/.config/bspwm/bspwmrc`

and comment this line

![Screenshot_2023-01-10-12-50-33_3840x1080](https://user-images.githubusercontent.com/62524855/211532096-ee82f9ac-104c-4a6c-8bcc-bc40b674520d.png)
