### ISSUE TITLE
UEFI boot not working

### ISSUE THREAD

**Issue by MelloHey** [Exodia-OS/exodia-home-ISO#8]
Trying to boot from USB with UEFI, not working on following devices...

Thinkpad T480
Dell XPS 9570

Just get presented with a black screen, waited up to 20 minutes and nothing happens.

Im stealing this issues to flag that legacy boot takes ages, stuck on copying rootfs to ram for alamost 30min before it boots into the os.

**Comment by IujyrinoT2** [comment]
Same on my Lenovo ideapad gaming 5 15IMH05. Been able to install arch and Nitrux just fine, but exodia won't even boot from usb, leaving me on a black screen.

**Comment by mmsaeed509** [comment]
all boot issues were resolved in the  [**`exodia-home-2023.07.06-x86_64.iso`**](https://drive.google.com/file/d/1d3btoTDUXLGt0Q4dWn2mCPcn15IIrLP3/view?usp=sharing) release

> If the blank screen appears again during booting
> Just wait about 2:5 mins and the system will boot up Inshallah

**recommend** to burn the ISO with [**`balena Etcher`**](https://etcher.balena.io/)
